---
apiVersion: v1
kind: Service
metadata:
  name: with-shard-enabled-v1-svc
spec:
  selector:
    app: with-shard-enabled-v1
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: with-shard-enabled-v2-svc
spec:
  selector:
    app: with-shard-enabled-v2
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---